name: am_player
description: A fast, private local video and audio player.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  on_audio_query: ^2.9.0
  flutter_bloc: ^8.1.6
  permission_handler: 12.0.3
  photo_manager: ^3.10.0
  just_audio_background: ^0.0.1-beta.9
  just_audio: ^0.9.46
  audio_service: ^0.18.19
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_android_video: ^1.3.8
  sqflite: ^2.4.2+1
  path_provider: ^2.1.6
  equatable: ^2.1.0
  simple_pip_mode: ^1.1.0
  path: ^1.9.1
  bloc: ^8.1.4
  meta: ^1.17.0
  flutter_screenutil: ^5.9.3
  file_picker: ^11.0.2
  package_info_plus: ^9.0.1
  share_plus: ^12.0.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dependency_overrides:
  just_audio_background:
    path: packages/just_audio_background

flutter:

  uses-material-design: true
  assets:
    - assets/images/audio_cover.png
    - assets/images/branding/splash_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/branding/app_icon.png
  adaptive_icon_background: "#111317"
  adaptive_icon_foreground: assets/images/branding/splash_logo.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#111317"
  color_dark: "#111317"
  image: assets/images/branding/splash_logo.png
  image_dark: assets/images/branding/splash_logo.png
  android: true
  ios: false
  web: false

  android_12:
    color: "#111317"
    color_dark: "#111317"
    image: assets/images/branding/splash_logo.png
    image_dark: assets/images/branding/splash_logo.png
    icon_background_color: "#111317"
    icon_background_color_dark: "#111317"


