name: am_player
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path: ^1.8.2
  path_provider: ^2.0.12
  file_manager: ^1.0.1
  audio_manager: ^0.8.2
  on_audio_query: ^2.6.0
  audioplayers: ^3.0.1
  intl: ^0.18.0
  file_picker: ^5.2.5
  filesystem_picker: ^3.1.0
  provider: ^6.0.5
  http: ^0.13.5
  sleek_circular_slider: ^2.0.1
  page_transition: ^2.0.9
  flutter_spinkit: ^5.1.0
  flutter_bloc: ^8.1.2
  line_icons: ^2.0.1
  on_audio_room: ^2.2.1+1
  permission_handler: ^10.2.0
  permission_handler_android: ^10.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  photo_manager: ^2.5.2
  photo_gallery: ^1.1.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


