name: am_player
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  on_audio_query: ^2.6.0
  audioplayers: ^3.0.1
  intl: ^0.18.0
  page_transition: ^2.0.9
  flutter_spinkit: ^5.1.0
  flutter_bloc: ^8.1.2
  permission_handler: ^10.2.0
  permission_handler_android: ^10.2.0
  photo_manager: ^2.5.2
  video_player: ^2.5.1
  better_player: ^0.0.83
  flick_video_player: ^0.5.0
  chewie: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


